#!/usr/bin/env python3
"""
Export Stage 1 safety results to Excel for human review.

Reads .batch_stage1_results.pkl + all_questions.xlsx
Produces: stage1_review.xlsx with columns:
  - Original columns (题目, 模型的答案, etc.)
  - safety_label: Safe / Unsafe / Controversial / Unknown
  - categories: comma-separated detected categories
  - raw_response: full text generated by safety model
"""

import os
import pickle

import pandas as pd
from loguru import logger

STAGE1_OUTPUT = os.environ.get("STAGE1_OUTPUT", "data/.batch_stage1_results.pkl")
INPUT_FILE = os.environ.get("INPUT_FILE", "all_questions.xlsx")
REVIEW_FILE = os.environ.get("REVIEW_FILE", "stage1_review.xlsx")


def main():
    logger.info("=" * 60)
    logger.info("Export Stage 1 Results for Review")
    logger.info(f"Input (Stage1): {STAGE1_OUTPUT}")
    logger.info(f"Input (Excel):  {INPUT_FILE}")
    logger.info(f"Output:         {REVIEW_FILE}")
    logger.info("=" * 60)

    if not os.path.exists(STAGE1_OUTPUT):
        logger.error(f"Stage 1 results not found: {STAGE1_OUTPUT}")
        logger.error("Please wait for batch_stage1_safety.py to finish.")
        return

    if not os.path.exists(INPUT_FILE):
        logger.error(f"Input file not found: {INPUT_FILE}")
        return

    # Load Stage 1 results
    with open(STAGE1_OUTPUT, "rb") as f:
        stage1_data = pickle.load(f)

    xls = pd.ExcelFile(INPUT_FILE)
    review_sheets = {}

    for sheet_name in xls.sheet_names:
        if sheet_name not in stage1_data:
            logger.warning(f"[{sheet_name}] No Stage 1 data, skipping.")
            continue

        df = pd.read_excel(xls, sheet_name=sheet_name)
        results = stage1_data[sheet_name]["results"]

        # Build review columns
        safety_labels = []
        categories_list = []
        raw_responses = []

        for r in results:
            safety_labels.append(r.get("safety") or "Unknown")
            cats = r.get("categories", [])
            categories_list.append(", ".join(cats) if cats else "")
            raw_responses.append(r.get("raw", ""))

        # Add/overwrite columns
        df["safety_label"] = safety_labels
        df["categories"] = categories_list
        df["模型的答案"] = raw_responses  # overwrite with safety model raw output

        review_sheets[sheet_name] = df

        safe = sum(1 for s in safety_labels if s == "Safe")
        unsafe = sum(1 for s in safety_labels if s in ("Unsafe", "Controversial"))
        unknown = sum(1 for s in safety_labels if s == "Unknown")
        logger.info(
            f"[{sheet_name}] Safe={safe}, Unsafe/Controversial={unsafe}, Unknown={unknown}"
        )

    # Write review Excel
    with pd.ExcelWriter(REVIEW_FILE, engine="openpyxl") as writer:
        for sheet_name, df in review_sheets.items():
            df.to_excel(writer, sheet_name=sheet_name, index=False)

    logger.info("=" * 60)
    logger.info(f"Review file saved: {REVIEW_FILE}")
    logger.info("Please review the safety classifications before running Stage 2.")
    logger.info("=" * 60)


if __name__ == "__main__":
    main()
